---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: ProfileName
        pluginConfig:
        - name: "DefaultEvictor"
        - name: "RemovePodsViolatingInterPodAntiAffinity"
        - name: "LowNodeUtilization"
          args:
            thresholds:
              "cpu" : 35
           targetThresholds:
              "cpu" : 50
       plugins:
          balance:
            enabled:
              - "LowNodeUtilization"
          deschedule:
            enabled:
              - "RemovePodsViolatingInterPodAntiAffinity"
